name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publicar no servidor
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Publicar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/database/**
